### ISSUE TITLE
Gallery Review Feedback

### ISSUE THREAD

**Issue by delsonting** [PropelMediaPlatform/GTM_Template#1]
Please fix the two items in order for this template to be included in the Gallery:

1) On line 55 use [encodeUriComponent](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) to encode data.trackingPixelID and data.commission to ensure the url is valid.
`const url = 'https://tracking.propelmedia.com/?id=' + data.trackingPixelID + '&fetch=2&value=' + data.commission;`

2) On line 60, the `data.gtmOnFailure();` call should be in an else statement. The intention is that gtmOnFailure or gtmOnSuccess should be called exactly once during template execution.

**Comment by PropelMediaPlatform** [comment]
Hi Google Team,

Thank you for the quick review.  I have made the two changes and updated the sha version for the new template commit within metadata.yaml.

Could you please let me know if this is sufficient for publishing the template?

**Comment by delsonting** [comment]
Approved, the template should be live in the Gallery within the next day. Thanks for the quick turnaround!
